name: Check Formatting

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run Prettier
        uses: creyD/prettier_action@v4.6
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --check .